version: '3'

services:
  # One of the services should listen on 8080 port
  # and has a defined alias on `director_versions` network.
  # In this example configureation it is the `app` service.
  app:
    build:
      context: ./app
    # The tag has DEPLOY_NS variable in it,
    # this is to prevent collisions if two people deploy
    # the same container the same time but with different version inside.
    # The `-app` suffix is there to share one Docker Hub repository
    # for different services with just tags. Saves money for small teams :)
    image: ${DOCKER_USER}/versions:${DEPLOY_NS}-app
    env_file: ${DEPLOYMENT_ENV}.env
    depends_on:
      - redis
    networks:
      default:
      director_versions:
        aliases:
         - '${DIRECTOR_VARIANT}'
    restart: always

  redis:
    image: redis:3.0
    restart: always

networks:
  director_versions:
    external: true
